apiVersion: v1
kind: Pod
metadata:
  name: worker-app-pod
  labels:
    name: worker-app-pod
    app: demo-votingapp
spec:
  containers:
    containers:
    - name: worker-app
      image: dockersamples/examplevotingapp_worker
      resources:
        limits:
          memory: "1Gi"
        requests:
          memory: "512Mi"
